// All supported symbols in the scanner
export type SymbolCode = "XAUUSD" | "EURUSD" | "GBPJPY" | "GBPUSD";

// Scan request payload coming from the dashboard
export interface ScanFilters {
  minRr?: number;
  spreadCap?: number;
}

export interface ScanParams {
  atrWindow?: number;
  structureLookback?: number;
  trendLookback?: number;
}

export interface ScanOptions {
  symbols?: SymbolCode[];
  filters?: ScanFilters;
  params?: ScanParams;
  date?: string;
}

// Single OHLC bar (daily in your current setup)
export interface OhlcBar {
  date: string;   // ISO yyyy-mm-dd (UTC is fine)
  open: number;
  high: number;
  low: number;
  close: number;

  // Optional extras from broker CSV
  spread?: number;      // broker spread (points/pips as exported)
  tickVolume?: number;  // tick volume column (TICKVOL)
  volume?: number;      // actual volume column (VOL)
}

// Orderblock / cluster zone object
export interface OcZone {
  zone_low: number;
  zone_high: number;
  zone_mid: number;
  score: number;
  // Optional semantic tag if you start classifying zones
  // e.g. "Demand", "Supply", "Resistance", etc.
  zone_type?: string;
}

// Map of highs/lows used for liquidity sweep logic
export interface LiquidityMap {
  highs: number[];  // all daily highs
  lows: number[];   // all daily lows
}

// Single trade candidate generated by the engine
export interface TradeCandidate {
  model: "A" | "B";
  direction: "Long" | "Short";
  entry: number;
  stop: number;
  tp1: number;
  risk_price: number;
  reward_price: number;
  rr: number;
  status: "VALID";
  stopType: "Swing" | "PD";
}

// Live price vs nearest zone snapshot for UI / decision support
export interface NearestZoneInfo {
  /** Live spot price at time of scan */
  spot: number;

  /** Zone geometry from the chosen OcZone */
  zone_low: number;
  zone_high: number;
  zone_mid: number;
  score: number;
  zone_type?: string;  // if present on OcZone

  /** Absolute distance in price units (from spot to zone_mid) */
  distance: number;

  /** Distance as % of price (distance / spot * 100) */
  distancePct: number;

  /** Distance in ATR multiples (optional, if ATR known) */
  distanceAtr?: number | null;

  /** Coarse proximity classification for UI */
  status: "AT_ZONE" | "NEAR" | "FAR";
}

// Per-symbol scan result
export interface SymbolScanResult {
  symbol: SymbolCode;
  trend: "Bull" | "Bear" | "Neutral";
  atr20: number;
  location: "Discount" | "Mid" | "Premium";
  zones: OcZone[];
  trades: TradeCandidate[];

  /** Optional live-price proximity info (if live prices are available) */
  nearestZone?: NearestZoneInfo | null;
}

// Top-level scan response returned by /api/scan
export interface ScanResponse {
  date: string;   // echo of query param or today
  symbols: Partial<Record<SymbolCode, SymbolScanResult>>;
}

// Static configuration for the scanner
export const CONFIG = {
  lookback_days: 20,        // window for zones & liquidity
  trend_lookback: 10,       // days to classify trend
  risk_cap: {
    XAUUSD: 40.0,           // ≈ $40 between Entry and SL
    EURUSD: 0.0040,         // 40 pips (0.0040 in price)
    GBPJPY: 0.0040,         // 40 pips (0.0040 in price) - JPY pairs
    GBPUSD: 0.0040          // 40 pips (0.0040 in price)
  } as Record<SymbolCode, number>,
  min_rr: 2.0,              // minimum Reward:Risk
  oc_cluster_radius: {
    XAUUSD: 5.0,            // $5 band for clustering O/C
    EURUSD: 0.0005,         // 5 pips
    GBPJPY: 0.0005,         // 5 pips - JPY pairs
    GBPUSD: 0.0005          // 5 pips
  } as Record<SymbolCode, number>,
  sl_buffer: {
    XAUUSD: 2.0,            // $2 beyond low/high or PDL/PDH
    EURUSD: 0.0005,         // 5 pips
    GBPJPY: 0.0005,         // 5 pips - JPY pairs
    GBPUSD: 0.0005          // 5 pips
  } as Record<SymbolCode, number>,
};
